services:
  - type: web
    name: my-portfolio
    runtime: node
    plan: free
    buildCommand: npm install && npm install --prefix server && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
